### PR TITLE
Fix link to documentation

### PR DESCRIPTION
**Pull request by henchies**
Link now points to more relevant documentation for this context

### CODE REVIEW

**Comment by bursauxa** [comment]
`http-proxy-middleware` is not used in ngx-rocket. We use `https-proxy-agent` which you can find [on github](https://github.com/TooTallNate/node-https-proxy-agent).

**Comment by henchies** [comment]
http-proxy-middleware gets included in a project if you generate it using ngx 6.4.1 using the below settings:

```
? What is the name of your app? ngx rock whatever
? What kind of app do you want to create? Web app
? Do you want a progressive web app? (with manifest and service worker) No
? Which UI framework do you want? Bootstrap (more website-oriented)
? Do you want authentication? No
? Do you want lazy loading? No
? Do you want analytics support (with Angulartics2)? No
? Do you want automatic code formatting with Prettier? Yes
```

The package-lock.json will contain http-proxy-middleware from start.
I made sure http-proxy-middleware is really being used by modifying some of its logger outputs in `\node_modules\http-proxy-middleware\lib\index.js` and confirming that the changes got reflected in the terminal when running the project using `npm start`. (For example, I modified `logger.info('[HPM] ...` to `logger.info('[HPM] asdf...`, then ran `npm start` and the change got reflected in the terminal)

Also, there's another reference to http-proxy-middleware in [backend-proxy.md](https://github.com/ngx-rocket/generator-ngx-rocket/search?q=http-proxy-middleware&unscoped_q=http-proxy-middleware).

**Comment by sinedied** [comment]
Actually the right link to the doc for the v7 version of the CLI is this one: https://angular.io/guide/build#using-corporate-proxy 😉

**Comment by bursauxa** [comment]
Closed by #457.

**Pull request closed without merging**
