### PR TITLE
async/await e2e and disable selenium promise manager (closes #399)

### LINKED ISSUE #399: switch to async/await tests and turn off SELENIUM_PROMISE_MANAGER
## I'm submitting a...

- [ ] Bug report  
- [x] Feature request
- [ ] Documentation issue or request

## Current behavior

tests are relying on SELENIUM_PROMISE_MANAGER to handle async control flow and keep our tests non-ugly, but it's being deprecated.

## Expected behavior

we're on node 8+ with native async/await, so we can turn it off and switch tests to using async/await and keep them pretty ;)

## Minimal reproduction of the problem with instructions

N/A

### PR DESCRIPTION
**Pull request by captaincaius**
deprecated SELENIUM_PROMISE_MANAGER now set to false so release/6.0 will be a little more future-proof ;)

### CODE REVIEW

**Comment by sinedied** [comment]
Perfect! It might also be useful to add a note on this and a link to https://www.protractortest.org/#/async-await in the e2e test guide 😉

**Comment by captaincaius** [comment]
Yup you're right - I'll try to add a commit to this PR tonight.  Maybe a quick note too saying that older examples you might find on the internet might be missing async/await because they might have had it enabled or something.

**Comment by captaincaius** [comment]
Hmm... something up w/ the appveyor builds?  Seems unrelated to the PR.

**Comment by sinedied** [comment]
Yes it's strange, maybe related to latest ng-cli update :/
Since travis is OK, we can merge this anyways after you've updated the docs.

**Comment by captaincaius** [comment]
> Perfect! It might also be useful to add a note on this and a link to https://www.protractortest.org/#/async-await in the e2e test guide

Donezo.  maybe I got a little carried away with the advertisements to protractor's docs but at least it's super clear :D.  LMK if it needs revision.

**Comment by sinedied** [comment]
That's perfect 😉

**Pull request merged**
