### PR TITLE
Add CircleCI config to build Cordova/Android paths

### PR DESCRIPTION
**Pull request by Ekhozie**
First part of #162 
Add CircleCi configuration to build android image with cordova
Another PR will come for iOS build
I had to create a specific docker image to build with cordova (no CircleCi predefined images was available with the good tools). I create a specific docker image in repository https://github.com/ngx-rocket/circleci-dockerfiles to add needed tools

### CODE REVIEW

**Comment by Ekhozie** [comment]
Maybe it's a better to squash changes on merge ? (lot of temporary commits to test the CI 😁)

**Comment by sinedied** [comment]
Good idea, I'll do a squash merge to cleanup the commits tree 😉

**Comment by sinedied** [comment]
@Ekhozie As a final sugar, you can add the CircleCI badge to the readme file, see: https://shields.io
(also add the circleCI logo to the badge, so we can distinguish it from the other, see at the bottom of the shields website)

**Comment by Ekhozie** [comment]
Good idea 😄, done.

**Pull request merged**
