### PR TITLE
Add Angular 8 support (close #478)

### LINKED ISSUE #478: Support for Angular 8
Is there any support for angular 8 migration?

### PR DESCRIPTION
**Pull request by sinedied**
Additional notable changes:
- Enable lazy loading by default
- Migrate services to use `providedIn`
- Add @ionic-native/keyboard package for Cordova target
- Disable AOT for serve task, to speed up rebuilds

### CODE REVIEW

**Comment by alexartwww** [comment]
Waiting for this release

**Comment by galenp** [comment]
I'm getting a compilation error with angular 8.0.2 that I don't think was occurring in 8.0.0.

`
ERROR in ./src/app/core/http/http.service.ts 30:12-27
"export 'HttpInterceptor' was not found in '@angular/common/http'
`

Might want to check that this PR is using 8.0.2 and is compiling successfully.

**Comment by sinedied** [comment]
This one migration has been particularly awful, and it's not even enabling Ivy or new lazy-loading system (tried it, didn't work 🤣).
Hopefully this will me mergeable soon🤞

**Comment by sinedied** [comment]
Finally! 🎉 🍾 🎊 😃 
Seems that CI flakyness (#480) with Ionic 4 also solved itself with the upgrade 😎

**Pull request merged**
