### PR TITLE
[WIP] Feature/ionic4

### PR DESCRIPTION
**Pull request by iocaste**
I have taken https://github.com/ngx-rocket/generator-ngx-rocket/pull/335, fixed comments regarding typescript and ported to work with latest changes that master has regarding #231

Started porting to Ionic v4

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for your contribution!

Though it seems there's some issues with your changes:
```
ERROR in src/app/app.component.ts(7,26): error TS2307: Cannot find module '@ionic-native/keyboard/ngx'.
src/app/app.component.ts(8,27): error TS2307: Cannot find module '@ionic-native/status-bar/ngx'.
src/app/app.component.ts(9,30): error TS2307: Cannot find module '@ionic-native/splash-screen/ngx'.
```

Also, we have a some PR to merge before this one can be merged, and the latest angular/cli release has some nasty bugs that broke the CI, so we're stuck until it's fixed for now.

**Comment by captaincaius** [comment]
Hi @iocaste 

I hadn't noticed you already had a PR that's quite far along yesterday, so I started porting a stock generated ngx-rocket project so I can have an overview of the differences.  You can see the diff here: https://github.com/captaincaius/ngxrocket501toionic4beta/pull/1/files

I see your PR is pretty far along (I didn't touch the generator itself yet), but I wanted to offer some help if it's possible.

If you think it's not really practical and you wanna finish it, then let me know if it would be helpful to you for me to continue refining the port so you can use it as a checklist of sorts for your PR.  For example, from looking at the differences, the errors @sinedied mentioned above seem to be from the package updates.

Thanks!
Al

**Comment by captaincaius** [comment]
Oh also, as a slightly-related vision question for @sinedied ...

Do you intend to abandon ionic 3 entirely and just get ionic 4 working?  Or do you want to see it as a separate option?

**Comment by iocaste** [comment]
@captaincaius Would be great if you could finish porting ionic-4. I saw that there is another PR that adds ionic tabs, looks like work for porting ionic 4 should be started from beginning.

**Comment by iocaste** [comment]
@sinedied Can you accept this PR https://github.com/ngx-rocket/generator-ngx-rocket/pull/361 ?
Looks like only thing that you wanted, was commit squash, it can be done from your side. This PR is needed so that we could have ionic-4 version with tabs and sidebar.

**Comment by captaincaius** [comment]
Great!  I'll be happy to help.

But guys, I'm a little unclear what direction this is going with the multi-layout PR in mind...

It seems that in 5.0.1 there was the following options:

- ionic (no layout options)
- material
  - simple layout
  - side-menu layout
- ... others...

After the PR you linked, it will be:

- ionic
  - side-menu layout (the same as 5.0.1)
  - tabs layout (new)
- material
  - simple layout
  - side-menu layout
- ... others...

So for the port, 
- will ionic 4 be maintained alongside ionic 3, or will it replace it?  If it'll replace it, I think it would be easier to port THEN add tabs.
- will both layouts need to be ported over?  If so, I should run the generator from that branch instead of master before starting the work?

Thanks!

**Comment by sinedied** [comment]
@iocaste The PR for the tabs will be merged as soon as the CI is done, I was waiting for other commit to be merged before (cordova fix and circleCI builds)

@captaincaius I don't think it makes sense to keep a Ionic 3 path as it won't be maintained now that the v4 is out. As it has some hard Angular version dependencies anyways, if anyone want to generate a ionic 3 project an old ngx rocket version can still be used.
So this PR should completely replace the Ionic 3 code by Ionic 4, and move on from there 😃

**Comment by captaincaius** [comment]
That sounds like a smart plan to me.  Maintaining ionic 3 as well would have been messy :D.

Okay, so with that in mind, which one of these options would you like me to do?

1. branch off master and only port the one layout - the tabs PR will need to be redone for ionic4 in that case
2. branch off the tabs PR now and port both layouts, and then once the squashed tabs it's merged, reroll a PR for the new master
3. wait for the tabs PR to merge, then start the port for both layouts

**Comment by sinedied** [comment]
I've merged the tabs branch, so now you can go for option 3) 😉

**Comment by captaincaius** [comment]
thanks :) on it today

**Comment by captaincaius** [comment]
quick update...

I ported most of the generated tabs over.

I made this PR to give you a chance to see the diffs more clearly than the PR I'm about to make for the generator itself.

https://github.com/captaincaius/ngx-rocket-20180825toionic4-tabs/pull/1/files

**Comment by captaincaius** [comment]
and FYI, it's functional and the tests pass, but I didn't fully update the styling, because it looks like it's still very much in flux over at ionic.

**Comment by iocaste** [comment]
I'm closing this PR as captaincaius took this task.

**Pull request closed without merging**
