### PR TITLE
Add support to generate PWA solution

### PR DESCRIPTION
**Pull request by R0muald**
Angular team created a new library that helps to generate web worker (@angular/service-worker), by adding `"serviceWorker": true,` in the `angular-cli.json` file, the build  (only on prod) will generate all associated files needed like `worker-basic.js`, `manifest.json` and `sw-register.js`.

The PWA option is accessible when selecting either web or cordova app. 

Should correspond to #93 feature.

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for the PR!

I have a few questions though:
- why did you change the `target` questions to a `list` (single-choice) only? The web and cordova (and in the future, electron) targets have different goals but can be built from the same codebase, it is valid use case to be able to build both a web and cordova app.
- why did you remove the `web` condition on the PWA question? (`when: props => props.target.includes('web')`). The web target includes a few additions needed for PWA (favicon, robots.txt, touch icon...) as a PWA is essentially an extension of a web app.

**Comment by R0muald** [comment]
Hi,
I knew you would ask that ^^ I guess I'm still confused about the form itself.
For me selecting Web means that I get a web design (web app/ web site like) and if I pick Cordova, I should end up with a mobile like application (ionic). So PWA should be accessible for both...

Maybe it's just about the wording we use. maybe the first question should be "web first (web site, web app)" vs "native first ( electron and/or cordova)", then we can ask if they want WPA, then design style (ionic or responsive)...

**Comment by sinedied** [comment]
You are right, maybe the distinction is not clear enough, some work is needed to clarify this...
In the meantime, here is how I see things:

- The target platform is **where** the app is destined to run: the web, mobile apps (cordova), desktop apps (electron), and so on (smartwatch, fridge, ...). You can have multiple targets, regardless of the design.

- The UI library choice is **how the app should look**: Bootstrap (more web-oriented), Ionic (more mobile-oriented), and in the future Angular material (suitable for both web and mobile). By default the generator suggest you an UI library depending of your platform choices (Bootstrap for web-only, Ionic for Cordova apps) but ultimately it's not forbidden to use Bootstrap to create a mobile app for example.

- All UI template should be *responsive* and usable and all kind of screen sizes.

I would like to keep options open, so a web app started with Bootstrap can also become a mobile app, and on the opposite a mobile app built on Ionic could also become a web app (and even better, a PWA) so the target should not be exclusive.

With this in mind, that's why I think PWA is  be more an "option" of the web platform as technically it's a web app++ 😉

**Comment by sinedied** [comment]
@R0muald do you wish to make the changes or do you prefer that I fix it directly?

**Comment by sinedied** [comment]
I fixed a few things, here is the result using https://github.com/ngx-rocket/addon-firebase for deployment:
pasted image at 2017_09_25 02_28 pm 1
😎

**Comment by sinedied** [comment]
For reference, the changes made to your initial implementation were based on: https://medium.com/@amcdnl/service-worker-pwas-with-the-angular-cli-98a8f16d62d6

**Comment by sinedied** [comment]
@R0muald: I just saw that your are not displayed among project contributors. To allow your commits to be properly displayed by Github, you should add the email address used in your git config to your github account (multiple emails can be used) 😉

**Pull request merged**
