### PR TITLE
Publish to gh-pages #278 - Service Workers relative path

### PR DESCRIPTION
**Pull request by reflexdemon**
Hi,

Here is a PR for #278.  Publish to gh-pages - service worker relative path.

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks, I'll just do a sanity check with a cordova build and merge it

**Comment by reflexdemon** [comment]
@sinedied 

Do you know what could have caused the below?

```
yarn run v1.5.1
$ ng lint --type-check && stylelint "src/**/*.scss" --syntax scss && htmlhint "src" --config .htmlhintrc
'ng' is not recognized as an internal or external command,
operable program or batch file.
error An unexpected error occurred: "Command failed.

```

**Comment by sinedied** [comment]
@reflexdemon That was an issue fixed with another PR, it should be ok now that I updated the branch.

Before merging I want to make sure this works with cordova builds, but when I tested with Android I had an (unrelated) issue that I need to fix first, so it's taking a bit more time 😕

**Comment by reflexdemon** [comment]
Thanks for response. I was curious to see if I could be of any help here.

**Comment by sinedied** [comment]
Just tested on mobile, it does not change anything, so it's good to merge :)

**Pull request merged**
