### PR TITLE
Remove lodash inclusion in projects, use vanilla JS instead

### PR DESCRIPTION
**Pull request by sinedied**
Since TypeScript support has improved a lot regarding collection-related methods available in ES7, lodash can now be safely removed as a default library. Vanilla JS FTW! ❤️

### CODE REVIEW

**Comment by bursauxa** [comment]
I myself consider Lodash to still be a very valuable asset, and preferrable to vanilla JS in most cases that go beyond basic include checks.

Typically, let's have a look at the changes you made in the HTTP cache service with commit 57aa238. Replacing `_.each` with `Object.entries.forEach` is a reasonable change on the surface. However, a more lodash-y way of performing the entire operation in the first place would have been to use `_.pickBy` ([docs](https://lodash.com/docs/#pickBy)), which removes one nested lambda while conveying the intent in a clearer fashion. And of course, this is not Vanilla JS...

**Comment by sinedied** [comment]
@bursauxa Sure I won't deny the fact that Lodash is still valuable (could not go without it in my current project :wink:), but in the case of the starter template usage it doesn't add much value, even though it slightly improves readability in the use case you cited.

I think it's good thing to have the least dependencies as possible in the starter template, but then maybe add an option to add those kind of go-to libraries directly. For now, I can think of Lodash and Moment.js, but maybe some others could be considered?

**Comment by bursauxa** [comment]
@sinedied Agreed, I was thinking along those lines: remove lodash from the base version but add it as an option. Ideally it would save people who missed the Lodash train from adding Underscore to their project :grin:

Moment is the only other library I can think of right now. Looking at the [top of the NPM package list](https://www.npmjs.com/browse/depended), I'd say everything else is already covered by Angular or strictly for Node.js development.

**Comment by sinedied** [comment]
Closing this one, replaced by #452

**Pull request closed without merging**
