### PR TITLE
feat: upgrade the generate app to be Angular 12 #600

### PR DESCRIPTION
**Pull request by patelvimal**

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for the PR!

I saw that e2e tests were removed from the default CLI template, though I would prefer to keep it here as an option as this generator is oriented towards enterprise apps which needs e2e tests most of the time.

I'll merge this in the ng12 work branch in the meanwhile, so I can also have a look at why the tests are failing (probably related to e2e removal).

**Comment by patelvimal** [comment]
Protector e2e is removed from angular 12 version. That's why I removed it.

**Comment by sinedied** [comment]
Yes, saw that. I'll use your PR as a basis to make it optional in the next release 🙂

**Comment by patelvimal** [comment]
ok, thanks, let me know how can I contribute more or do you have any other interesting angular project to contribute?

**Pull request merged**
