### PR TITLE
Add angular-material UI choice

### PR DESCRIPTION
**Pull request by dvaJi**
Ref to #124
I don't know if this new option should be added to [ngx-core](https://github.com/ngx-rocket/core) or extend it. IMO,it's better add it to core.

### CODE REVIEW

**Comment by sinedied** [comment]
Thanks for the submission, I'll take a look at it ❤️ 

You are right for the option, I'll add it to the core dependency ASAP.

**Comment by sinedied** [comment]
I just published a new `@ngx-rocket/core` `3.0.0` version with the `material` prefix support, could you try it to fix the tests?

**Comment by sinedied** [comment]
Perfect! Are you ok if I merge this temporarily in a separate branch, so that I can push it a bit further? I would like to make the template responsive using the side menu component, integrate with [flex layout](https://github.com/angular/flex-layout) and replace font awesome with Material icons.

I have some of these additions WIP here: https://github.com/ngx-rocket/starter-kit/tree/feature/material, it would mostly be a matter of merging it as you did all the template work 👍

**Comment by dvaJi** [comment]
Sure! also, I've added a customizable scss but maybe could be good adding options to choose available pre-built themes like:
> deeppurple-amber.css
> indigo-pink.css
> pink-bluegrey.css
> purple-green.css

**Comment by sinedied** [comment]
That could be an idea, but since you already added customizable theming I think it's more flexible as you can already choose any color combination 😃

**Pull request merged**
