### PR TITLE
Leveled up e2e test example

### PR DESCRIPTION
**Pull request by captaincaius**

### CODE REVIEW

**Comment by bursauxa** [comment]
Thanks for the Pr @captaincaius. It looks good to me. The only thing I'm not fond of is the lack of any `expect(...)` in the login test. Maybe you could verify that test/123 was submitted ?

**Comment by captaincaius** [comment]
Thanks! :)

For this PR I didn't add or remove any actions or assertions compared to what was already in the e2e before - I wanted to make sure it was easy to see the little restructuring.

That being said, if you folks are happy with this approach, I'll be happy to add new assertions to it.

About verifying the submission, do you mean checking localStorage or something to verify that the login was successful?

**Comment by sinedied** [comment]
@captaincaius I approved your PR and changed the base to the newly created `release/6.0.x` branch.

Once the CI is ok it can be merged and used as a base for the Ionic 4 PR (as stated in your comment), so we can also (finally!) merge it.

The `6.0.x` branch will be used to publish an npm release under the `@next` tag, until Ionic 4 is stable enough to be considered for the main release.

Sorry for the huuuuuuge delay, I'm usually much more responsive but my freshly born 2nd boy made a big hit on my free time 😅

**Comment by captaincaius** [comment]
awesome possum! :) and congrats again on your new boy!

is there a place you'd like to keep a list of things blocking the 6.0 release?  there's already a few things on the ionic side IMO.

**Comment by sinedied** [comment]
BTW, I added you to the contributors of this project, you should now be able to merge PRs once validated by a review, participate in reviews and create feature branches directly on this repo among other things 😉
Thanks again for your contributions!

**Comment by captaincaius** [comment]
I feel very privileged to be in the same room as you folks! ;)

Very cool!  Thanks for the warm welcome! :)

**Pull request merged**
