### PR TITLE
Feature/strict options

### PR DESCRIPTION
**Pull request by sinedied**

### CODE REVIEW

**Comment by sinedied** [comment]
It seems that this PR/issue will be blocked until ionic@4 release: https://github.com/ionic-team/ionic/issues/14358#event-1597774293

**Comment by sinedied** [comment]
After https://github.com/ngx-rocket/generator-ngx-rocket/pull/369 is merged, I'll rebase this PR and it should be okay 🤞

**Comment by bursauxa** [comment]
#369 is now merged. @sinedied do you want to proceed with this one? I can have a look myself if you do not have time, but I'm always doubtful towards rebase operations.

**Comment by sinedied** [comment]
@bursauxa If you can take a look at it, do it and yes a merge here is probably the best idea given the shallow conflict surface 👍

**Pull request closed without merging**
