### PR TITLE
Synced up polyfills with latest angular CLI

### PR DESCRIPTION
**Pull request by captaincaius**
minor changes to polyfills comments...

NOTE: I didn't do this one: https://github.com/angular/angular-cli/commit/d3fa9a6631f816b4f0c059a1035a8b90ad3581c1#diff-7ed40e1057374060b6223a05a7046411

Is it safe for us?  I didn't see any explanation/issue/etc other than the commit message, so I wanted to be conservative and ask first.

### CODE REVIEW

**Comment by captaincaius** [comment]
looks like the deprecated ionic keyboard is suddenly making everything red.  Seems this failure is on master too.  Should we backport the change in the ionic4 branch to master?

**Comment by captaincaius** [comment]
As for this branch, syncing this after merging the to-ionic4 PR into 6.x should turn this green...

For master, I submitted this PR https://github.com/ngx-rocket/generator-ngx-rocket/pull/393 :)

**Comment by sinedied** [comment]
Thanks, I missed this in the v6 update 😛 

> NOTE: I didn't do this one: angular/angular-cli@d3fa9a6#diff-7ed40e1057374060b6223a05a7046411

> Is it safe for us? I didn't see any explanation/issue/etc other than the commit message, so I wanted to > be conservative and ask first.

As of now, only the unit tests runs in JIT mode due to CLI limitations, so I would say if they removed it and if our CI running the tests is OK with that, it should be safe to include 😄

**Comment by captaincaius** [comment]
Cool beans.  Good point - the comment said evergeen browsers need it, so I guess we can trust our tests to tell us :)

I see you updated this one.  I'll push a different PR with it removed so we know which one we can merge :)

Oh, do you want it on master too?

**Comment by captaincaius** [comment]
yup - https://github.com/ngx-rocket/generator-ngx-rocket/pull/394 failed, so this one wins. :)

**Pull request merged**
