### PR TITLE
WIP - use async/await

### PR DESCRIPTION
**Pull request by creal73**

### CODE REVIEW

**Comment by sinedied** [comment]
Is it a WIP? It's missing a few :wink:

**Comment by creal73** [comment]
Sorry, I forgot to leave a comment.

Do I miss something or there is not so much promises to convert ? 

I searched for ".then" or "Promise" and I found only two results on Ionic part...

**Comment by sinedied** [comment]
Did you try on `release/6.0.0x` branch 😉?

**Comment by creal73** [comment]
🤦‍♂️ my bad...

I close this PR to restart from `release/6.0.0x` branch.

**Pull request closed without merging**
